### ISSUE TITLE
is this MIT License?

### ISSUE THREAD

**Issue by frog-o** [HuyQLuong/vscode-webview-extension-with-react#1]
Is this under the MIT License?
It look almost identical to the example show for build a webview extension by Microsoft.   

I made some adjustment to your example they include:  Removing npm to use pnpm, change npm command to npx,  Remove strict false and set to strict true, up date the library to use react 18,  And got rid of the alias in package.json and use indirect reference instead.

I was think about forking this since i doubt you want these changes and to me they are important.  I wanted to do other improvement to this app too and I want to make sure I have the right to put it under the MIT licence.

**Comment by HuyQLuong** [comment]
Feel free to use it ! Star it if you like this repo !
