### ISSUE TITLE
How to add tailwind in this project?

### ISSUE THREAD

**Issue by haalcala** [HuyQLuong/vscode-webview-extension-with-react#2]
How to add tailwind in this project?

**Comment by zaghadon** [comment]
Did you figure it out? @haalcala .

Any thoughts here? @HuyQLuong

**Comment by HuyQLuong** [comment]
Hi guys, might be you could try by include Tailwind CSS via CDN

Add `<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">` into `<head>`

**Comment by HuyQLuong** [comment]
@zaghadon Do it resolved your issue ? If yes, I will close the issue here
