### ISSUE TITLE
useEffect doesn't work

### ISSUE THREAD

**Issue by SaadBazaz** [HuyQLuong/vscode-webview-extension-with-react#3]
Hey,
Cool repo. 
I've tried to use `useEffect` in `LeftPanel.tsx`, however, it doesn't fire.
What could be the reason?

**Comment by HuyQLuong** [comment]
If you check in LeftPanel.tsx, you could see they are using `ReactDOMServer.renderToString` which causing the useEffect does not fire.

If you want to use useEffect in this case, might need to build the React app by your own and load it into the vscode extension
